name = "nookure-frontend"

compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"